// ================================================================
//  projects.js — YOUR PORTFOLIO DATA
//  ────────────────────────────────────────────────────────────────
//  This is the ONLY file you need to edit to manage your projects.
//  index.html reads this automatically — never touch that file.
//
//  HOW TO ADD A PROJECT:
//  1. Open new-entry.html in your browser → fill the form → copy output
//  2. Paste the new entry at the TOP of the PROJECTS array below
//  3. Save this file — done.
//
//  FOLDER STRUCTURE FOR PHOTOS:
//  Put your photos inside the Portfolio folder like this:
//
//    Portfolio/
//    ├── index.html
//    ├── projects.js
//    └── Projects/
//        ├── 2026/
//        │   └── Project Name/
//        │       ├── thumb-1.jpg      ← shown on timeline card
//        │       ├── thumb-2.jpg
//        │       └── gallery-1.jpg   ← shown inside project detail
//        └── 2011/
//            └── Aviation - Piloting/
//                └── WP_000433.jpg   (already here)
//
//  Then reference photos as:  'Projects/2026/Project Name/thumb-1.jpg'
// ================================================================

const PROJECTS = [

  // ──────────────────────────────────────────────────────────────
  //  ↓  PASTE NEW ENTRIES HERE (newest at the top)  ↓
  // ──────────────────────────────────────────────────────────────
  {
    id:      'something-to-shoot',
    year:    '2023',
    yearTag: '2023 - Present',
    title:   ['Something to shoot'],
    cat:     'Audiovisual',
    thumbLayout: 'lay-duo-equal',
    thumbs: [
      'Projects/2023/something-to-shoot/8-DSC02538-topaz.webp',
      'Projects/2023/something-to-shoot/22-DSC07547.webp',
    ],
    text: [
      '"Taking my camera to latin nights at Dirty Laundry — a small venue you entered through a washing machine door, because why not — started as something to do with my hands in a social setting. The camera gave me a reason to move around, interact with everyone, blend in without having to be the most confident person in the room. People wanted photos, I wanted to shoot. It worked.',
      'By late July I was at Technical Dooficulties, a Doof party on the way to the Daintree — hidden location revealed the day of, camp overnight, the whole thing. Someone lent me a car, which still amazes me about this country. I\'d just upgraded from my Nikon D5300 to a Sony A6400 before leaving Chile, without really having the money to justify it. Don\'t regret it.',
      'That night I got introduced to a couple of Chilean guys putting together something called Wild — a party series with a concept behind it. Underwater themed one week, forest the next. Props at the entry, a whole environment built around the music, not just a dancefloor. One of them was playing, another learning to DJ live, the third one building the scenery. They needed content. I needed something to grow into.',
      'What followed was one of those periods that\'s hard to explain without sounding like you\'re exaggerating. I was working a 4am cleaning shift at the shopping centre before it opened, then pushing cases and running audio at the Convention Centre from 9 to 5, then Pizza Hut deliveries until 10pm — all of it to save enough to keep upgrading gear and show up ready for whatever Wild needed that weekend. New lenses, a couple of portable RGB lights, started shooting video and editing it too. Not my strongest skill at the time but I was growing alongside them.',
      'The last one I shot with them was at the Benson Hotel — rooftop, open air, completely different energy to a nightclub. Better for it. I had a drone by then, which meant getting back in the air in a way I hadn\'t expected, doing something I hadn\'t planned, and loving every second of it. The footage is up on YouTube.',
      'Wild is on a bit of a hiatus — still looking for the right venue to make it worth doing properly. In the meantime the work opened other doors. Other DJs started reaching out, bars and venues around town offered content work. The bandwidth from my end wasn\'t quite there to commit to it the way it deserved, but the interest is there and the setup keeps growing — Sony A7III with a 16-35mm f/1.8 and a 50mm f/1.4, a filter collection, two drones, a couple of DJI gimbals and an action camera for when one angle isn\'t enough. At some point the timing will line up."',
    ],
    gallery: [
      'Projects/2023/something-to-shoot/33-DSC02563-topaz.webp',
      { src: 'Projects/2023/something-to-shoot/8-DSC02538-topaz.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/14-DSC02517-topaz.jpg.webp', pos: '49.6% 63.7%', portrait: true },
      'Projects/2023/something-to-shoot/2-DSC07577.webp',
      'Projects/2023/something-to-shoot/47-DSC05465post.webp',
      { src: 'Projects/2023/something-to-shoot/29-DSC03607-topaz.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/2-DSC03647.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/22-DSC07547.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/10-DSC03699.webp', portrait: true },
      'https://youtu.be/hpvajVccLvQ',
      'https://youtu.be/zVN5lYNFKrY',
      { src: 'Projects/2023/something-to-shoot/20-DSC06716post.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/23-DSC06732post.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/17-DSC05579post.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/25-DSC06740post.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/26-DSC06751post.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/38-DSC07522.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/41-DSC07519.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/55-DSC04799post.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/207-DSC07325.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/145-DSC07389.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/151-DSC07382.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/63-DSC06984post.webp', portrait: true },
      'Projects/2023/something-to-shoot/1-DSC07578.webp',
      'Projects/2023/something-to-shoot/230-DSC07298.webp',
      { src: 'Projects/2023/something-to-shoot/70-DSC05366post.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/129-DSC04411post.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/128-DSC04412post.webp', portrait: true },
      { src: 'Projects/2023/something-to-shoot/69-DSC04713post.webp', portrait: true },
      { layout: 'feat-group', items: [
        { src: 'Projects/2023/something-to-shoot/66-DSC04735post.webp', portrait: true },
        'Projects/2023/something-to-shoot/61-DSC04761post.webp',
        'Projects/2023/something-to-shoot/108-DSC04500post.webp',
      ] },
    ],
  },
  {
    id:      'av-technician',
    year:    '2023',
    yearTag: '2023 - 2024',
    title:   ['The QR code', 'that changed everything'],
    cat:     'Audiovisual',
    thumbs: [
      { src: 'Projects/2023/av-technician/IMG_2675.webp', pos: '100% 180%' },
      'Projects/2023/av-technician/IMG_5663.webp',
      { src:'Projects/2023/av-technician/IMG_2280.webp', pos: '50 % 80%' },
    ],
    text: [
      '"Back in Chile, while I was preparing the move, a friend from home — Hector — gave me solid advice about having a long term plan for staying in Australia. He suggested development, even offered to help pay for it. I applied for a scholarship instead and got it. Bootcamp style, so on top of everything else I was doing to prepare the move, I was going deep into coding at night. The timing was tight — I had about a month before I had to leave.',
      'A couple of weeks after arriving in Australia I was doing what most of us do — sending applications and getting nowhere. The jetlag had me waking up at 3am craving pasta, so I restructured my mornings: 5am runs along the Esplanade to stay sane, then straight into classes. The bootcamp kept going, just from a different continent now — except the Saturday sessions ran 10am to 3pm back home, which landed at 11pm to 4am in Cairns. I think I made it to two or three of those before the library QR code changed my priorities entirely.',
      'One morning at the library, working through my classes, I walked past a QR code that said "we are hiring." I thought — wouldn\'t be too bad, sorting books, quiet environment, sounds perfect. What I found on that website instead was a casual Audiovisual Technician position at the Cairns Convention Centre. My first thought was something along the lines of — they\'re not going to care about a sound engineering degree from Chile, but I\'ll give it a go anyway.',
      'My live events experience back home was real but modest. Weddings, university welcome events, bands playing to a couple hundred people. The biggest was a pool party for around 1,000 — headlined by a Reggaeton singer who was apparently mildly famous. I had no idea who he was.',
      'Surprisingly, I got the call for an interview. I was so excited I didn\'t want to mess it up. I then proceeded to walk into the wrong entrance entirely — straight into the Arena from City Terrace, stopped by security and redirected to the proper staff entrance.',
      'My first shift was the 23rd of May, during the setup of Cannes in Cairns. Everything was new — the scale, the infrastructure, the technology. Dante networking, large format PA builds, LED walls, lighting consoles. None of my teachers had ever mentioned any of it. I knew enough to be useful but humble enough to know I had a lot to learn. I started reading manuals on my days off and keeping notes after every shift.',
      'The language didn\'t make it easier. The Australian accent is its own thing — fast, full of slang, words cut in half. I always say it\'s the English version of Chilean Spanish. For a while I was demonstrating competence through actions more than words — staying back when everyone else left at 5, finishing what needed to be finished, keeping moving when others stopped to talk. Now that I\'m supervising I understand exactly how much that gets noticed.',
      'My friends from the hostel were telling me constantly to go out, do road trips, enjoy the working holiday visa. I appreciated it. But I wasn\'t on holidays. I was here to stay. I am here to stay."',
    ],
    gallery: [
      'Projects/2023/av-technician/IMG_5663.webp',
      'Projects/2023/av-technician/IMG_4568.webp',
      'Projects/2023/av-technician/IMG_3178.webp',
      { src: 'Projects/2023/av-technician/IMG_3891.webp', pos: '49.6% 68.3%' },
      'Projects/2023/av-technician/IMG_4374.webp',
      'Projects/2023/av-technician/IMG_5557.webp',
      'Projects/2023/av-technician/IMG_5678.webp', 
      {src: 'Projects/2023/av-technician/IMG_4149.webp', portrait: true },
      { src:'Projects/2023/av-technician/IMG_4588.webp', portrait: true },
    ],
  },
  {
    id:      'the-place-i-chose-to-belong',
    year:    '2023',
    yearTag: '2023 - Present',
    title:   ['Australia:', 'The place I chose to belong'],
    cat:     'Personal',
    thumbs: [
      'Projects/2023/a-country-worth-fighting-for/69-DSC02049-topaz-denoise-sharpen.webp',
      { src: 'Projects/2023/a-country-worth-fighting-for/Aussie Flag.webp', pos: '48.2% 97%' },
      'Projects/2023/a-country-worth-fighting-for/IMG_2181.webp',
    ],
    text: [
      '"There\'s a point where effort stops feeling like investment and starts feeling like resistance. Chile had given me a lot — formative experiences, hard lessons, genuine creative moments — but it had also made clear, repeatedly, that the conditions for thriving weren\'t going to materialise on their own.',
      'The creative work had started to feel hollow. Not because of a lack of effort, but because the environment around it wasn\'t aligned with what making something is actually for. Music shouldn\'t be a vehicle for chasing relevance — it should be the place where something true gets made audible. When that stops being the shared understanding, the work stops meaning what it\'s supposed to mean.',
      'After lockdown, Tone Light faded with it. People had spent what they had during isolation and were now desperate to get back outside — not unreasonably. The timing had passed.',
      'A store manager role filled the gap. It paid the bills. Then one day three men walked in, put a knife to my throat, and took everything. My boss\'s response was to be upset that I hadn\'t done more to stop it.',
      'That same year, my first car — bought and rebuilt alongside my mechanic father, finished only weeks before — was involved in a crash that I didn\'t have any responsability in and the driver didn\'t want to pay for it. Shortly after, my ID was stolen. Someone used it to open credit cards and bank accounts in my name. Sorting out the roughly $20,000 AUD in fraudulent debt took months of time and energy I didn\'t have.',
      'At some point, the pattern becomes a message.',
      'Australia had been in the background my entire life. My uncle came here in the 80s. My parents had plans to follow — plans that didn\'t materialise for reasons I still don\'t have the full story on. Both versions exist and I haven\'t yet sat down with everyone involved to find out what actually happened. I will. I want to know, not to assign blame, but because it\'s part of where I came from.',
      'Growing up, Australia was always described as somewhere people actually got a fair go. That stayed.',
      'In 2022 I started making it concrete. Weighed up Brazil, Canada, parts of Europe — each had something, none of them had everything. Australia kept coming back. My closest friend Rodrigo was already making the move. That felt like a signal worth listening to.',
      'I sat the English test, sold everything — vinyls, sound and music gear, the car — and saved whatever I could. There were no savings to speak of. Everything had already been converted into things worth having.',
      'On the 3th of May 2023 I landed in Sydney, spent one night there where Rodrigo was already living, and flew to Cairns the next morning.',
      'The first few weeks were spent at Global Backpackers — ten people to a room, a shared kitchen, and the particular social pressure of hostel life. Not a natural environment for someone who doesn\'t lead with small talk, and even less so when the English wasn\'t yet flowing with confidence. Connections felt just out of reach.',
      'Then my friend Diego arrived three weeks later, checked into the same hostel, and within days had assembled a circle of people around him. He introduced me to all of them. I felt like I\'d cheated somehow — but I was grateful enough not to question it too hard.',
      'I still can\'t fully believe it happened.',
      'The clearest thing this move has taught me is simple: when the environment is right, thriving stops being a fight. It just starts happening."',
    ],
    gallery: [
      'Projects/2023/a-country-worth-fighting-for/IMG_2181.webp',
      'Projects/2023/a-country-worth-fighting-for/IMG_2573.webp',
      { src: 'Projects/2023/a-country-worth-fighting-for/IMG_2028.webp', pos: '50.6% 87%' },
      'Projects/2023/a-country-worth-fighting-for/IMG_1983.webp',
      { src: 'Projects/2023/a-country-worth-fighting-for/IMG_1966.webp', pos: '49.2% 24.3%' },
      'Projects/2023/a-country-worth-fighting-for/IMG_1825.webp',
      'Projects/2023/a-country-worth-fighting-for/d3921d10-8167-485d-8e46-c6a31be39a43.webp',
      'Projects/2023/a-country-worth-fighting-for/IMG_0500.webp',
      'Projects/2023/a-country-worth-fighting-for/23-DSC01891.webp',
      'Projects/2023/a-country-worth-fighting-for/DSC_7204-2.webp',
      'Projects/2023/a-country-worth-fighting-for/DSC_7202-2.webp',
      'Projects/2023/a-country-worth-fighting-for/99-1672795578231.webp',
      'Projects/2023/a-country-worth-fighting-for/29-1671415980108.webp',
      { src: 'Projects/2023/a-country-worth-fighting-for/6-DSC_0316(1)-topaz-denoise-faceai.webp', pos: '49.1% 88.4%' },
      { src: 'Projects/2023/a-country-worth-fighting-for/7-DSC02158-topaz-denoise.webp', pos: '50.3% 81.6%' },
      { src: 'Projects/2023/a-country-worth-fighting-for/IMG_2703.webp', pos: '57.6% 22.7%', portrait: true },
      { src: 'Projects/2023/a-country-worth-fighting-for/F3DDF784-6BD1-4902-BAE4-E7A32C6B320E.webp', portrait: true },
      'Projects/2023/a-country-worth-fighting-for/30-DSC02127-topaz-denoise-faceai.webp',
    ],
  },
    {
    id:      'tone-light',
    year:    '2020',
    yearTag: '2020 - 2023',
    title:   ['Tone', 'Light'],
    cat:     'Audiovisual - Entrepreneurship',
    thumbs: [
      'Projects/2020/tone-light/DSC_9923.webp',
      'Projects/2020/tone-light/EstudioNicobaja.webp',
      'Projects/2020/tone-light/POST-TONE-LIGHT_medio1080x1080_IG.webp',
    ],
    text: [
      '"Building a home studio meant making it a space worth spending time in. The first LED light was built for that reason — LED strips fed through carved wood, set into a concrete base. A personal project, not a product.',
      'Then people started asking if they could buy one.',
      'What followed was an exercise in figuring things out by necessity. Designing variations, sourcing RGBW wireless controllers that could sync with music, respond to voice commands and be managed from a phone. Setting up an e-commerce store, testing suppliers, iterating on components, balancing quality against what people were actually willing to pay. When demand grew, a 3D printer came into the picture — opening up new base designs, mounting systems and modular configurations that couldn\'t be done by hand alone.',
      'The clearest test of the whole operation came from a theatre company that needed a 10-metre horizontal lighting bar — modular, portable, and reliable enough to be assembled and disassembled at every venue. Designing connections that could take repeated use without failure, building a system that a non-technical crew could handle quickly. It worked.',
      'Tone Light ran its course and is no longer active, but it taught a specific kind of problem-solving — the kind where the brief, the budget, and the build are all yours to figure out."',


    ],
    gallery: [
      'Projects/2020/tone-light/1606399585516.webp',
      'Projects/2020/tone-light/1606399668171.webp',
      'Projects/2020/tone-light/DSC_9801.webp',
      {src: 'Projects/2020/tone-light/DSC_0871.webp', portrait: true },
      {src:'Projects/2020/tone-light/DSC_9923.webp', portrait: true },
      { src: 'Projects/2020/tone-light/DSC_0860.webp', pos: '48.2% 90.6%', portrait: true },
      { src: 'Projects/2020/tone-light/Moon-Black-1.webp', pos: '50.6% 69.5%', portrait: true },
      {src:'Projects/2020/tone-light/IMG_20211214_110209.webp' },
      'Projects/2020/tone-light/tone light moon.webp',
      'Projects/2020/tone-light/18-DSC_0341.webp',
      'Projects/2020/tone-light/7_2_2022, 22_38_44.webp',
      { src: 'Projects/2020/tone-light/Tone Light Bar.webp', pos: '87.2% 42.7%' },
      { src: 'Projects/2020/tone-light/tone Light Bar 2.webp', pos: '85.6% 44.3%' },
      { layout: 'feat-group', items: [
        { src: 'Projects/2020/tone-light/IMG-20210418-WA0034.webp', portrait: true },
        { src: 'Projects/2020/tone-light/14-DSC_0345.webp' },
        { src: 'Projects/2020/tone-light/16-DSC_0343.webp' },
      ] },
    ],
  },
  {
    id:      'home-studio',
    year:    '2020',
    yearTag: '2020-2023',
    title:   ['Home', 'Studio'],
    cat:     'Audiovisual',
    thumbs: [
      'Projects/2020/home-studio/DSC_7211.webp',
      'Projects/2020/home-studio/DSC_7220.webp',
      'Projects/2020/home-studio/DSC_0261.webp',
    ],
    text: [
      '"The home studio came together in the final semester of my degree — built to record personal projects and occasionally bring in other artists. It never paid the bills, but it didn\'t need to. It was the space where the technical and creative sides of the training finally met on my own terms.',
      'When COVID hit, having that setup already in place meant work could continue remotely without interruption — a practical advantage that turned a hobby investment into a professional one almost overnight.',
      'Once that chapter closed, the studio became something more personal. Time opened up to focus on music in a way that hadn\'t been possible before — working with aspiring artists and occasionally with musicians operating at a professional level. Nothing built for scale, but everything built with care.',
      'The studio didn\'t make the move to Australia. The Apollo interface and the Maschine did."',
    ],
    gallery: [
      'Projects/2020/home-studio/DSC_1614.webp',
      'Projects/2020/home-studio/DSC_0261.webp',
      'Projects/2020/home-studio/DSC_2011.webp',
      'Projects/2020/home-studio/DSC_7211.webp',
      'Projects/2020/home-studio/DSC_7220.webp',
    ],
  },
   {
    id:      'chaos-in-santiago',
    year:    '2019',
    yearTag: '2019 - 2020',
    title:   ['Social', 'Uprising'],
    cat:     'Audiovisual - Photography',
    thumbLayout: 'lay-duo-equal',
    thumbs: [
      'Projects/2019/chaos-in-santiago/DSC_3788.webp',
      'Projects/2019/chaos-in-santiago/DSC_3595.webp',
    ],
    text: [
      'Some images in this section document the 2019 Chilean social uprising. They are unfiltered and may be confronting.',
      '"My first camera was a Nikon D5300, bought in January 2019. The part that hooked me wasn\'t the shooting — it was the editing. Taking an ordinary place and pulling out something that wasn\'t immediately visible. Adjusting colour, contrast, light until reality became a slightly better version of itself. I found that process quietly addictive.',
      'That approach lasted until October of that year.',
      'Chile\'s social uprising began over a 30 pesos increase in public transport fares — roughly 6 Australian cents. The slogan that spread across the country said it plainly: it\'s not 30 pesos, it\'s 30 years. Thirty years of policies built for the few, wages that couldn\'t cover a cost of living that rivalled cities like Sydney or Melbourne, and institutions that seemed structurally designed to protect themselves rather than the people inside them.',
      'It was not abstract to me. I was working full time without a contract, without sick leave, without paid leave, without guaranteed hours, and without any of the protections that in Australia are considered basic. A large, established company doing this routinely, without consequence. The frustration on the streets made complete sense.',
      'At its peak, two million people marched down the main avenue in Santiago. Neighbourhoods filled with the sound of people hitting pots and pans — cacerolazo — each person finding their own way to be heard. Some kept it peaceful. Others dismantled footpaths and built fire barricades. I didn\'t share their method. My instinct was that a destroyed street sign represented hundreds of dollars that could have funded a school or a hospital. But I understood the rage underneath it, even when I couldn\'t follow the logic of the action.',
      'Then the president declared that the country was at war with a powerful enemy and deployed the military.',
      'Tanks on the street I took to work. Tanks outside my window. I opened it from the second floor to get a closer look. My partner at the time leaned out and shouted at them to go back to their barracks. They pointed at us.',
      'I have never felt my heart move like that before or since.',
      'My camera came with me after that, despite the risk of having it taken or destroyed by police or military. The editing approach changed completely. No colour grading. No pulling beauty out of the ordinary. Just exposure, shadows, colour temperature — enough to see clearly. The rawness was the point. The ugliness was the document.',
      'Looking back at those images, I can see the mistakes clearly — blown exposure, soft focus, acrylic red and cyan filters that I thought added something and only degraded the image. That\'s part of it. I was learning, and I was present, and I documented something real.',
      'The uprising didn\'t ultimately land where many of us hoped. In many ways it divided the country more than it united it. But I remain proud of the people who had the courage to stand in the street and say that things needed to change — even when the response was a declaration of war against their own citizens."',
    ],
    gallery: [
      { src: 'Projects/2019/chaos-in-santiago/DSC_3058.webp', pos: '49.5% 96.6%' },
      {layout: 'feat-group', items: [
        { src: 'Projects/2019/chaos-in-santiago/DSC_3179.webp', pos: '49.5% 92%', portrait: true },
        'Projects/2019/chaos-in-santiago/DSC_3064.webp',
        'Projects/2019/chaos-in-santiago/DSC_4664.webp',
      ]},
      'Projects/2019/chaos-in-santiago/DSC_3188.webp',
      'Projects/2019/chaos-in-santiago/DSC_3231.webp',
      'Projects/2019/chaos-in-santiago/DSC_3241.webp',
      'Projects/2019/chaos-in-santiago/DSC_3249.webp',
      'Projects/2019/chaos-in-santiago/DSC_3330.webp',
      { src: 'Projects/2019/chaos-in-santiago/DSC_3419.webp', pos: '50.2% 38.3%' },
      { src: 'Projects/2019/chaos-in-santiago/DSC_3437.webp', pos: '50.4% 4.9%', portrait: true},
      {src: 'Projects/2019/chaos-in-santiago/DSC_3595.webp', portrait: true},
      { src: 'Projects/2019/chaos-in-santiago/DSC_3601.webp', pos: '50.5% 42.7%', portrait: true},
      { src: 'Projects/2019/chaos-in-santiago/DSC_3769.webp', pos: '51.1% 70.1%', portrait: true},
      {layout: 'feat-group', items: [
        {src: 'Projects/2019/chaos-in-santiago/DSC_3788.webp', portrait: true},
        {src: 'Projects/2019/chaos-in-santiago/DSC_3777.webp'},
        'Projects/2019/chaos-in-santiago/DSC_3989.webp',
      ]},
      { src: 'Projects/2019/chaos-in-santiago/DSC_4030.webp', pos: '48% 14.8%' , portrait: true},
      {src: 'Projects/2019/chaos-in-santiago/DSC_4141.webp', portrait: true},
      { src: 'Projects/2019/chaos-in-santiago/DSC_4193.webp', pos: '54.1% 89%', portrait: true},
      { src: 'Projects/2019/chaos-in-santiago/DSC_4221.webp', pos: '51.4% 95.2%', portrait: true},
      {layout: 'feat-group', items: [
        { src: 'Projects/2019/chaos-in-santiago/DSC_4611.webp', pos: '46.5% 19.4%', portrait: true},
      'Projects/2019/chaos-in-santiago/DSC_4257.webp',
      'Projects/2019/chaos-in-santiago/DSC_4530.webp',
      ]},
      { src: 'Projects/2019/chaos-in-santiago/DSC_4637.webp', pos: '55.3% 96%', portrait: true},
      {src: 'Projects/2019/chaos-in-santiago/DSC_4661.webp', portrait: true},
      {layout: 'feat-group', items:[
        { src: 'Projects/2019/chaos-in-santiago/DSC_4690.webp', pos: '46.2% 54.4%' , portrait: true},
        'Projects/2019/chaos-in-santiago/DSC_4693.webp',
        'Projects/2019/chaos-in-santiago/DSC_4694.webp',
      ]},
    ]},
  {
    id:      'foley',
    year:    '2019',
    yearTag: '2019-2020',
    title:   ['Foley'],
    cat:     'Audiovisual',
    thumbs: [
      'Projects/2019/foley/DSC_0010.webp',
      'Projects/2019/foley/DSC_1678.webp',
      'Projects/2019/foley/1568780793452.webp',
    ],
    text: [
      '"During my Sound Engineering studies, an internship placement led me to DINT — Doblajes Internacionales, Chile\'s leading dubbing studio, producing content for Discovery Networks, Netflix, Nickelodeon and others.',
      'It started with shadowing. Watching the senior technicians work was humbling — recording dialogue while simultaneously editing the previous take, catching the faintest saliva noise in an actor\'s mouth, and making real-time decisions when a translated phrase didn\'t match the timing or weight of the original performance. The standard was uncompromising and the pace relentless.',
      'The part of the operation that captured my attention most was the Foley department — a room that looked like organised chaos but contained everything deliberately. Every object had a purpose. That creative logic made immediate sense to me.',
      'I was introduced to a Native Instruments Kontakt library setup within Pro Tools — a MIDI-triggered footstep library covering surfaces, textures and shoe types, used to handle lighter Foley workload and free up the main studios for more complex work. I picked it up quickly, started covering for the regular operator, and when a night shift Foley position opened up, they offered it to me.',
      'It was effectively full-time work without a contract — a known reality in a field where the opportunity itself is considered the privilege, especially in Chile and across South America. I accepted without hesitation. The access to that environment and that level of work was worth it at the time.',
      'Then COVID closed the studios.',
      'I\'d been building a home studio in parallel, which meant I could keep working when others couldn\'t. The workflow adapted — projects moved through Google Drive instead of internal folders, sessions downloaded and uploaded between departments remotely. The challenge was the environment: living in central Santiago meant construction noise, traffic, horns and buses bleeding into recordings constantly, adding unpredictability to every session.',
      'As delays stacked up across departments, the pressure on the business grew. When the studios partially reopened under government permit restrictions, those permits required proof of employment — a contract. I didn\'t have one, so I was out.',
      'A few months later they called. My answer to my boss Pedro was simple: I\'d come back with a contract, or not at all.',
      'I didn\'t go back."',
    ],
    gallery: [
      'Projects/2019/foley/1546905064061.webp',
      'Projects/2019/foley/1546905063701.webp',
      'Projects/2019/foley/1547165715802.webp',
      'Projects/2019/foley/DSC_1678.webp',
      { src: 'Projects/2019/foley/DSC_1680.webp', pos: '52.7% 98.9%' },
      { src: 'Projects/2019/foley/IMG_20190107_091313.webp', pos: '54.6% 98.4%' },
      { src: 'Projects/2019/foley/IMG_20190111_090604.webp', pos: '33.6% 34.9%' },
      { src: 'Projects/2019/foley/IMG_20190405_175220.webp', pos: '48.2% 31.1%' },
      'Projects/2019/foley/IMG_20200319_113650.webp',
    ],
  },
    {
    id:      'field-sound-recording',
    year:    '2018',
    yearTag: '2018',
    title:   ['Sound Field', 'Recording'],
    cat:     'Audiovisual',
    thumbs: [
      'Projects/2018/field-sound-recording/IMG_0855.webp',
      'Projects/2018/field-sound-recording/IMG_1445.webp',
      'Projects/2018/field-sound-recording/IMG_0723.webp',
    ],
    text: [
      'During my Sound Engineering studies, I completed a course in sound field recording — capturing dialogue, wildtracks, and ambience at the highest quality for use in post-production, where sound and image are shaped into a finished piece.',
      'In 2018, that training got its first real test. I had the opportunity to work on "Por mi y por todas", a short film created and directed by a group of final-year audiovisual communication students as their degree project.',
      'It was my first recorded and post-produced audiovisual work — and it came with every challenge that implies.',
    ],
    gallery: [
      'Projects/2018/field-sound-recording/IMG_0728.webp',
      'Projects/2018/field-sound-recording/IMG_0842.webp',
      'Projects/2018/field-sound-recording/IMG_0855.webp',
      'Projects/2018/field-sound-recording/IMG_1240.webp',
      'Projects/2018/field-sound-recording/IMG_1445.webp',
      'Projects/2018/field-sound-recording/IMG_1457.webp',
      'Projects/2018/field-sound-recording/IMG_0723.webp',
    ],
  },
  {
    id:      'sound-engineering',
    layout:  'thread',          // story thread: pairs each gallery image with text[i]
    thread:  'sweeping',        // taut | sweeping | meander
    year:    '2015',
    yearTag: '2015 - 2020',
    title:   ['Sound', 'Engineering'],
    cat:     'Audiovisual',
    thumbLayout: 'lay-duo-equal',
    thumbs: [
      { src: 'Projects/2015/sound-engineering/DSC_5003.webp', pos: '46% 50.4%' },
      { src: 'Projects/2015/sound-engineering/IMG_4630.webp', pos: '64.9% 53.4%' },
    ],
    text: [
      'Warning: Some of these photos were retrieved from the digital equivalent of a shoebox under the bed. Quality not guaranteed.',
      '"The decision came down to simple math — the cost of a single year of commercial pilot training would cover an entire Sound Engineering degree. After years of structure, regulations, and a strict physical appearance code, the freedom alone felt like oxygen.',
      'The years between aviation and university weren\'t wasted. Travelling through Chile, working whatever paid the bills, I was quietly rebuilding a creative life — teaching myself guitar, experimenting with Ableton Live, buying a MIDI keyboard and figuring things out by ear. The Chilean indie scene was quietly growing into something exciting, and I wanted to be part of it.',
      'Choosing Sound Engineering over Music Production was a pragmatic call. Music production was the dream; sound engineering was the foundation that could support it. The tradeoff felt clear enough at the time.',
      'The early years were underwhelming. Coming in with a strong background in physics and maths from aviation studies, much of the curriculum didn\'t offer the stimulation I needed. That changed in the later semesters with Acoustics — modelling spaces in AutoCAD, SketchUp and Vectorworks, running them through EASE to analyse acoustic parameters, calculating speech clarity, music definition, and using impulse response simulation to predict how a space would actually sound before it was ever built. That clicked something back into place.',
      'Sound Design and Post Production did the same — discovering the relationship between sound and the visual language of film pointed my compass firmly toward audiovisual production. I added a photography elective outside my program just because I could, and found myself thriving in the overlap between disciplines.',
      'The degree culminated in an experimental short film — assembled from stock footage into an original story, with a full original score and post production created by the team. We performed it live while the film played behind us. It was ambitious for the timeline we had: 3–4 months, other coursework running in parallel, and most of us holding down jobs on the side. We chose to make it harder than it needed to be, and it was worth it.',
      'Finishing the degree was the right call. It became the foundation that made immigrating to Australia possible, and with it, a career that finally feels proportional to the effort put in — fair wages, genuine opportunities, and enough stability to focus on the work itself rather than surviving around it. The events industry is anything but predictable. Late changes, shrinking budgets, and the unpredictable human element are part of the job. It keeps you sharp."',
    ],
    gallery: [
      'Projects/2015/sound-engineering/IMG_4630.webp',
      { src: 'Projects/2015/sound-engineering/IMG_1418.webp', pos: '88% 72.7%', portrait: true },
      {src: 'Projects/2015/sound-engineering/IMG_5513.webp', portrait: true}, 
      { src: 'Projects/2015/sound-engineering/IMG_0347.webp', pos: '45.7% 32.3%' },
      { src: 'Projects/2015/sound-engineering/IMG_0700.webp', pos: '85.3% 19%' },
      'Projects/2015/sound-engineering/IMG_20181129_001518.webp',
      'Projects/2015/sound-engineering/IMG_20181129_001624.webp',
      'https://youtu.be/Y3JAt6Wa0Rw?si=SJLjXqfypJ6ZuBJI',
      'Projects/2015/sound-engineering/IMG_20181129_011911.webp',
    ],
  },
     {
    id:      'aviation-piloting',
    year:    '2012',
    yearTag: '2012 - 2013',
    title:   ['Aviation and', 'Aeronautics'],
    cat:     'Aviation',
    thumbLayout: 'lay-duo-equal',
    thumbs: [
      { src: 'Projects/2012/aviation-piloting/on-the-air.webp', pos: '21.9% 59.6%' },
      { src: 'Projects/2012/aviation-piloting/SAM_0634.webp', pos: '52.9% 70.9%' },
    ],
    text: [
      '"Since being a kid, the idea that something as massive and heavy as a commercial aircraft could be lifted off the ground and carry hundreds of people — each one with their own dreams, goals, and destinations — to the other side of the world never stopped being extraordinary.',
      'Coming from a lower-income background, this was not a conventional career path. The cost of training was significant, and that cost kept growing — each year, contracts became more expensive, making the investment harder to sustain.',
      'What ultimately made the path harder to continue wasn\'t the challenge itself, but what the industry revealed over time. Competence and effort didn\'t always translate to outcomes. Watching capable, qualified people not get the positions they had worked toward made it difficult to keep investing in a system where merit wasn\'t the clear deciding factor.',
      'The pivot was toward something that had been there since childhood as well — sound, and through sound, music. That decision became the first real thread in a longer story, and eventually the reason to be able to immigrate to Australia altogether."',
    ],
    gallery: [
      { src: 'Projects/2012/aviation-piloting/on-the-air.webp', pos: '46.5% 73.3%' },
      'Projects/2012/aviation-piloting/SAM_0705.webp',
      'Projects/2012/aviation-piloting/DSC05735.webp',
      'Projects/2012/aviation-piloting/2012-07-26 15.50.03 (2).webp',
      'Projects/2012/aviation-piloting/DSCN2839.webp',
      'Projects/2012/aviation-piloting/SAM_1048.webp',
      'Projects/2012/aviation-piloting/SAM_1070.webp',
      'Projects/2012/aviation-piloting/SAM_0584.webp',
      'Projects/2012/aviation-piloting/SAM_0629.webp',
      'Projects/2012/aviation-piloting/SAM_0559.webp',
      'Projects/2012/aviation-piloting/WP_000304.webp',
      'Projects/2012/aviation-piloting/SAM_1001.webp',
      'Projects/2012/aviation-piloting/WP_000161.webp',
      'Projects/2012/aviation-piloting/cabina 2.webp',
      'Projects/2012/aviation-piloting/cabina 1.webp',
      'Projects/2012/aviation-piloting/WP_000057.webp',
      'Projects/2012/aviation-piloting/SAM_0648.webp',
      'Projects/2012/aviation-piloting/Tren.webp',
      'Projects/2012/aviation-piloting/Turbina.webp',
      'Projects/2012/aviation-piloting/SAM_0609.webp',
      'Projects/2012/aviation-piloting/WP_000316.webp',
    ],
  },
];
